# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Diagnostic Companion (spec §20, §13.1).

Build:
    pyinstaller diag.spec --clean --noconfirm

Notes that matter more than the config below:

**Data files are not optional.** pattern_kb/ and policy/ are the
tool's knowledge. If they fail to bundle, the binary still starts and
reports every machine as healthy, because no rules means no findings.
cli.py calls resources.assert_data_files_present() at startup to turn
that into a loud failure. The datas list here and
resources.REQUIRED_DATA_FILES are checked against each other by
tests/test_resources.py.

**One file vs. one directory.** onefile is chosen for distribution
(a technician downloads one thing), at the cost of unpacking to a temp
directory on every run — which adds startup time and is itself a
pattern some AV products treat as suspicious (§13.1). If Defender
proves hostile to the onefile build, the first thing to try is
onedir, which does not self-extract. That is a real fallback, not a
theoretical one, which is why the build script exposes both.

**UPX is disabled deliberately.** Compressed executables are heavily
correlated with malware packing in AV heuristics. The size saving is
not worth the reputation cost for a tool that already has to explain
itself to SmartScreen.
"""

import os

block_cipher = None

# Imported rather than restated, so the spec and the startup check can
# never disagree about what has to ship.
from resources import DATA_DIRS

datas = [(d, d) for d in DATA_DIRS if os.path.isdir(d)]

a = Analysis(
    ["cli.py"],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[
        # Collector modules are selected at runtime by platform, so the
        # dependency graph does not reach them statically.
        "collectors.core.system", "collectors.core.network",
        "collectors.core.disk", "collectors.core.logs",
        "collectors.optional.battery", "collectors.optional.wifi",
        "collectors.optional.smart",
        "collectors.windows.system", "collectors.windows.network",
        "collectors.windows.disk", "collectors.windows.logs",
        "collectors.windows.battery", "collectors.windows.wifi",
        "collectors.windows.smart",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Trim the bundle: none of these are used, and every megabyte is
    # more surface for an AV scanner to think about.
    excludes=["tkinter", "matplotlib", "numpy", "pandas", "PIL", "pytest",
              "setuptools", "pip", "unittest"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="diag",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,          # see module docstring
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,       # this is a CLI tool; a GUI-less build would hide output
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Version metadata helps a human (and, marginally, SmartScreen)
    # identify the binary. Generated by build.py when on Windows.
    version="version_info.txt" if os.path.exists("version_info.txt") else None,
    # Embedded so the executable carries its own icon in Explorer and
    # the taskbar, and so a shortcut can point at the exe when no
    # separate .ico ships alongside it.
    icon=os.path.join("launchers", "icons", "diag-icon.ico")
         if os.path.exists(os.path.join("launchers", "icons", "diag-icon.ico")) else None,
)
