"""Corroboration — comparing what two or more hosts saw.

Pure. Observations in, findings out, no clock and no disk of its own.

Four rules, and three of them are about refusing to overclaim:

**1. Disagreement about the gateway is the prize.** If two hosts on the same
segment hold different MACs for the gateway IP, at least one of them has
been lied to. That is far stronger than anything a single ARP cache can
say, and it is the one finding here that earns `critical`.

**2. Agreement is NOT proof.** Two hosts can agree and both be wrong — one
attacker poisoning both caches produces perfect consensus. Agreement raises
confidence; it never establishes truth, and the wording says so. Getting
this backwards would build a machine that manufactures false comfort, which
is worse than the single-cache blindness it set out to fix.

**3. One observation is not corroboration.** A lone file corroborates
nothing, and must say so rather than reporting quiet agreement with itself.

**4. A stale observation is not evidence about now.** A host that has been
off since yesterday describes yesterday's network. Past a freshness window
it stops counting as a witness — and that is reported, not silently
dropped, because a corroboration that quietly shrank to one observer looks
identical to one that succeeded.

**5. A host that saw NOTHING is not a witness.** Added 2026-07-27, after a
process on a machine with no LAN visibility wrote a well-formed observation
into a shared directory: `readable: true`, no gateway, no neighbours. It was
counted, `host_count` read 2, and every device the real host could see was
reported as "seen by only one of 2 hosts" — a page of findings generated by
comparing a network against an empty set. `readable` means the tool ran, not
that it saw anything, and the gap between those two is exactly where a false
witness fits.
"""

from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional, Sequence

from contracts import Finding
from contracts.finding import Coverage
from contracts.observation import Observation

#: How old an observation may be and still describe "now". An hour matches
#: the patrol cadence: any host that is awake and patrolling has written
#: within the window, and any host that has not is genuinely not a witness.
DEFAULT_MAX_AGE_MINUTES = 90


def _parse(ts: str) -> Optional[datetime]:
    try:
        parsed = datetime.fromisoformat(ts)
    except (TypeError, ValueError):
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)


def age_minutes(obs: Observation, now: datetime) -> Optional[float]:
    """How old this observation is, or None if its timestamp is unusable."""
    when = _parse(obs.observed_at)
    if when is None:
        return None
    return (now - when).total_seconds() / 60.0


def saw_nothing(obs: Observation) -> bool:
    """True when this host reported successfully and observed no network.

    `readable` says the tool RAN. It says nothing about whether there was a
    LAN in front of it — a container, a machine with its interface down, or
    a host on an isolated network all produce a perfectly well-formed
    observation describing nothing at all. Counting one as a witness turns
    "nobody else can see this" into "another host disagrees", which is the
    opposite of what corroboration is for.
    """
    return not obs.gateway_ip and not obs.neighbours


def fresh(observations: Sequence[Observation], now: datetime,
          max_age_minutes: int = DEFAULT_MAX_AGE_MINUTES):
    """Split into (usable witnesses, stale-or-undated-or-empty ones).

    An observation with an unreadable timestamp is treated as stale, not as
    fresh: the safe direction is to drop a witness we cannot date rather
    than to count one that may describe last week. An observation that saw
    nothing is dropped for the same reason and reported the same way — never
    silently, because a corroboration that quietly shrank to one observer
    looks identical to one that succeeded.
    """
    usable, stale = [], []
    for obs in observations or []:
        age = age_minutes(obs, now)
        if age is None or age > max_age_minutes or age < -5:
            stale.append(obs)               # -5: tolerate small clock skew
        elif saw_nothing(obs):
            stale.append(obs)               # present, but not a witness
        else:
            usable.append(obs)
    return usable, stale


def distinct_hosts(observations: Sequence[Observation]) -> int:
    """How many DIFFERENT machines are represented.

    The same host's file counted twice is one witness, not two — which is
    the difference between corroboration and an echo.
    """
    return len({o.machine_id for o in (observations or []) if o.machine_id})


def _coverage(observations) -> Coverage:
    readable = sum(1 for o in observations if o.readable)
    return Coverage(checked=readable, total=len(observations))


def segments(observations: Sequence[Observation]) -> Dict[str, List[Observation]]:
    """Group witnesses by the gateway IP they answer to.

    **Two hosts on different subnets have different gateways, and comparing
    their gateway MACs is meaningless.** Without this the code compared every
    observation against every other, so a laptop on 192.168.1.0/24 and a
    desktop on 192.168.1.0/24 would produce two different gateway MACs and be
    reported as ARP spoofing — a critical alert manufactured out of ordinary
    network topology. Corroboration only means anything WITHIN a segment.
    """
    grouped: Dict[str, List[Observation]] = {}
    for obs in observations or []:
        if obs.gateway_ip:
            grouped.setdefault(obs.gateway_ip, []).append(obs)
    return grouped


def gateway_disagreement(observations: Sequence[Observation],
                         machine_id: str) -> List[Finding]:
    """The finding this whole feature exists for.

    Compares only hosts that share a gateway IP — see `segments`.
    """
    findings: List[Finding] = []
    for gateway_ip, group in sorted(segments(observations).items()):
        findings += _one_segment(gateway_ip, group, machine_id, observations)
    return findings


def _one_segment(gateway_ip: str, group: Sequence[Observation],
                 machine_id: str, everyone: Sequence[Observation]) -> List[Finding]:
    claims: Dict[str, List[str]] = {}
    for obs in group:
        if obs.gateway_mac:
            claims.setdefault(obs.gateway_mac.lower(), []).append(obs.machine_id)
    if len(claims) < 2:
        return []

    detail = "; ".join(f"{mac} (seen by {', '.join(sorted(hosts))})"
                       for mac, hosts in sorted(claims.items()))
    observations = everyone
    return [Finding(
        id=f"corroboration_gateway_mac_conflict_{gateway_ip}",
        source_module="lan-anomaly",
        machine_id=machine_id,
        severity="critical",
        confidence="certain",
        message=(f"Hosts DISAGREE about the MAC of {gateway_ip}: {detail}. "
                 "At least one of these machines has been given a false "
                 "answer for the gateway — the signature of ARP spoofing."),
        coverage=_coverage(observations),
        suggested_action=(
            "Compare each host's ARP entry for the gateway against the MAC "
            "printed on the router. Do not trust the segment until they "
            "agree. Run `capture` on both machines now, while it is live."),
        tags=("security", "corroboration"),
    )]


def only_one_host_sees(observations: Sequence[Observation],
                       machine_id: str) -> List[Finding]:
    """Devices visible from one vantage point and not the other.

    Deliberately `info`. On a switched network this is ordinary: a host only
    holds ARP entries for machines it has recently talked to, so two hosts
    routinely see different subsets. It is context for a human reading a
    census, not a finding to wake anyone.
    """
    if distinct_hosts(observations) < 2:
        return []
    seen_by: Dict[str, List[str]] = {}
    for obs in observations:
        for ip in obs.neighbours:
            seen_by.setdefault(ip, []).append(obs.machine_id)

    hosts = {o.machine_id for o in observations}
    lonely = sorted(ip for ip, who in seen_by.items() if len(set(who)) == 1)
    if not lonely:
        return []
    return [Finding(
        id="corroboration_partial_visibility",
        source_module="lan-census",
        machine_id=machine_id,
        severity="info",
        confidence="certain",
        message=(f"{len(lonely)} device(s) were seen by only one of "
                 f"{len(hosts)} hosts: {', '.join(lonely[:8])}"
                 + (" …" if len(lonely) > 8 else "")),
        coverage=_coverage(observations),
        suggested_action=(
            "Normal on a switched network — a host only holds ARP entries "
            "for machines it has spoken to recently. Worth a look only if a "
            "device you expected everywhere shows up in one place."),
        tags=("census", "corroboration"),
    )]


def assess(observations: Sequence[Observation], machine_id: str,
           now: datetime,
           max_age_minutes: int = DEFAULT_MAX_AGE_MINUTES) -> List[Finding]:
    """Every corroboration finding, from the fresh witnesses only."""
    usable, _stale = fresh(observations, now, max_age_minutes)
    if distinct_hosts(usable) < 2:
        return []                           # nothing to compare; see `verdict`
    return gateway_disagreement(usable, machine_id) + \
        only_one_host_sees(usable, machine_id)


def verdict(observations: Sequence[Observation], now: datetime,
            max_age_minutes: int = DEFAULT_MAX_AGE_MINUTES) -> dict:
    """The state of corroboration itself, separate from what it found.

    Returned even — especially — when there is nothing to compare. "No
    finding" and "no second witness" are different facts, and a caller that
    could not tell them apart would report an unwitnessed network as an
    agreeing one.
    """
    usable, stale = fresh(observations, now, max_age_minutes)
    hosts = sorted({o.machine_id for o in usable})
    unreadable = [o.machine_id for o in usable if not o.readable]

    # Corroboration is per-SEGMENT. Two witnesses on different subnets are
    # two witnesses to different networks, which corroborates nothing — and
    # must not be reported as though it did.
    by_segment = segments(usable)
    biggest = max((set(o.machine_id for o in g) for g in by_segment.values()),
                  key=len, default=set())
    shared = len(biggest) >= 2
    gateways = {o.gateway_mac.lower()
                for g in by_segment.values() for o in g
                if o.gateway_mac and len({x.machine_id for x in g}) >= 2}

    # "Went quiet" and "is here but saw nothing" are different problems with
    # different fixes, so they are reported apart rather than as one number.
    blind = sorted({o.machine_id for o in stale if saw_nothing(o)})
    gone = sorted({o.machine_id for o in stale if not saw_nothing(o)})

    return {
        "hosts": hosts,
        "host_count": len(hosts),
        "can_corroborate": shared,
        "segments": {ip: sorted({o.machine_id for o in g})
                     for ip, g in sorted(by_segment.items())},
        "split_across_segments": len(by_segment) > 1,
        "stale": gone,
        "blind": blind,
        "unreadable": sorted(set(unreadable)),
        "gateway_agreement": (len(gateways) == 1) if shared and gateways else None,
        "max_age_minutes": max_age_minutes,
    }
