#!/usr/bin/env bash
# ====================================================================
#  Install a desktop launcher (Linux).
#
#      ./install-desktop-entry.sh            install
#      ./install-desktop-entry.sh --remove   uninstall
#
#  Unlike the USB launcher, this one may use absolute paths: it points
#  at a binary installed at a fixed location on this machine, so the
#  relative-path problem that makes .desktop files unsuitable for
#  removable media does not apply here.
#
#  Two details that are easy to get wrong and produce a launcher that
#  silently does nothing:
#
#    * Terminal=true is NOT used, despite this being a console program.
#      GNOME dropped its built-in handling in favour of the
#      xdg-terminal-exec spec, which many distributions ship no provider
#      for — the launcher then silently does nothing. A wrapper
#      (diag-window) opens a terminal explicitly and the entry sets
#      Terminal=false, which works everywhere.
#    * Icon= is an absolute path, not a theme name. A theme name needs
#      the icon cache refreshed and fails silently when unresolved,
#      which some file managers render as no icon at all.
#    * GNOME and Nautilus refuse to run a .desktop file on the Desktop
#      unless it is executable AND marked trusted. Both are done below;
#      omitting the second is why desktop shortcuts commonly show up as
#      a text file icon instead.
# ====================================================================

set -u

# This script lives in launchers/linux/; the project root is two up.
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HERE="$(cd -P "$SCRIPT_DIR/../.." && pwd)"
APP_ID="diagnostic-companion"

# The desktop folder is localised: it is ~/Desktop on an English
# install and ~/Bureaublad, ~/Skrivbord or ~/Работна површина
# elsewhere. Hardcoding "Desktop" means the copy silently does nothing
# on any non-English system - the script reports success and no icon
# ever appears. xdg-user-dir knows the real path.
desktop_dir() {
    local dir=""
    if command -v xdg-user-dir >/dev/null 2>&1; then
        dir="$(xdg-user-dir DESKTOP 2>/dev/null)"
    fi
    # xdg-user-dir returns $HOME when no desktop folder is configured,
    # which would scatter a .desktop file into the home directory.
    if [ -n "$dir" ] && [ "$dir" != "$HOME" ] && [ -d "$dir" ]; then
        echo "$dir"
        return
    fi
    [ -d "$HOME/Desktop" ] && echo "$HOME/Desktop"
}
DESKTOP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
ICON_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/scalable/apps"
ENTRY="$DESKTOP_DIR/$APP_ID.desktop"

if [ "${1:-}" = "--remove" ]; then
    DESK="$(desktop_dir)"
    rm -f "$ENTRY" "$ICON_DIR/$APP_ID.svg" \
          "$HOME/.local/bin/diag-window" "$HOME/.local/bin/diag-from-source"
    [ -n "$DESK" ] && rm -f "$DESK/$APP_ID.desktop"
    command -v update-desktop-database >/dev/null 2>&1 && \
        update-desktop-database "$DESKTOP_DIR" 2>/dev/null
    echo "Removed."
    exit 0
fi

# Prefer the built binary; fall back to running from source so this is
# useful before anyone has run build.py.
if [ -x "$HERE/dist/diag" ]; then
    DIAG_TARGET="$HERE/dist/diag"
    echo "Using built binary: $DIAG_TARGET"
elif [ -x "$HERE/dist/usb-kit/diag" ]; then
    DIAG_TARGET="$HERE/dist/usb-kit/diag"
    echo "Using USB-kit binary: $DIAG_TARGET"
elif [ -f "$HERE/cli.py" ]; then
    PY="$HERE/.venv/bin/python"
    [ -x "$PY" ] || PY="$(command -v python3)"
    # A two-word command; the wrapper quotes $DIAG_BIN as one path, so
    # wrap the source invocation in its own tiny shim instead.
    SHIM="$HOME/.local/bin/diag-from-source"
    mkdir -p "$HOME/.local/bin"
    printf '#!/usr/bin/env bash\nexec "%s" "%s" "$@"\n' "$PY" "$HERE/cli.py" > "$SHIM"
    chmod +x "$SHIM"
    DIAG_TARGET="$SHIM"
    echo "No binary found - running from source via $PY"
    echo "  (run 'python3 build.py' first for a standalone launcher)"
else
    echo "Cannot find diag or cli.py next to this script." >&2
    exit 1
fi

BIN_DIR="$HOME/.local/bin"
mkdir -p "$DESKTOP_DIR" "$ICON_DIR" "$BIN_DIR"

# The wrapper opens a terminal explicitly. DIAG_BIN is baked in so the
# .desktop file needs no shell quoting gymnastics of its own.
WRAPPER="$BIN_DIR/diag-window"
if [ -f "$SCRIPT_DIR/diag-window" ]; then
    {
        echo "#!/usr/bin/env bash"
        echo "# Generated by install-desktop-entry.sh — do not edit."
        echo "export DIAG_BIN=\"$DIAG_TARGET\""
        tail -n +2 "$SCRIPT_DIR/diag-window"
    } > "$WRAPPER"
    chmod +x "$WRAPPER"
    echo "Wrapper: $WRAPPER"
else
    echo "launchers/linux/diag-window is missing." >&2
    exit 1
fi

# Absolute path, not a theme name: a theme name depends on the icon
# cache being refreshed and fails silently when it is not.
#
# The explicit chmod matters. The repository may hold this file as 0600
# (it lives on a mount that forces restrictive modes), and cp preserves
# that. An icon the desktop shell cannot read renders as the generic
# document glyph with no error anywhere — indistinguishable from a
# wrong path.
ICON="utilities-system-monitor"   # stock fallback: always resolvable
PNG_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/256x256/apps"
mkdir -p "$PNG_DIR"

# SVG first (scales cleanly), PNG as a companion. Some shells and file
# managers handle one better than the other, and installing both costs
# 25KB.
for pair in "diag-icon.svg:$ICON_DIR/$APP_ID.svg" "diag-icon.png:$PNG_DIR/$APP_ID.png"; do
    src="$HERE/launchers/icons/${pair%%:*}"
    dst="${pair#*:}"
    [ -f "$src" ] || continue
    if cp "$src" "$dst" 2>/dev/null; then
        chmod 0644 "$dst" 2>/dev/null || true
        if [ -r "$dst" ]; then
            ICON="$dst"
            echo "Icon: $dst"
        else
            echo "Icon copied but not readable - falling back to a stock icon."
        fi
    fi
done

cat > "$ENTRY" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=Diagnostic Companion
GenericName=System Health Check
Comment=Read-only health check of this computer - changes nothing
Exec=$WRAPPER
Icon=$ICON
Terminal=false
Categories=System;Monitor;Utility;
Keywords=diagnostic;health;disk;smart;battery;wifi;report;
Actions=Check;Report;Decode;

[Desktop Action Check]
Name=Check this computer now
Exec=$WRAPPER

[Desktop Action Report]
Name=Save a report I can send on
Exec=sh -c "'$DIAG_TARGET' run --format html -o \"\$HOME/diagnostic-report-\$(hostname)-\$(date +%Y-%m-%d_%H%M).html\"; printf '\\n  Press Enter to close. '; read x"

[Desktop Action Decode]
Name=Look up a Windows error code
Exec=sh -c "printf '  Error code: '; read c; '$DIAG_TARGET' decode \"\$c\"; printf '\\n  Press Enter to close. '; read x"
EOF

chmod +x "$ENTRY"
chmod 0755 "$ENTRY" 2>/dev/null || true

command -v update-desktop-database >/dev/null 2>&1 && \
    update-desktop-database "$DESKTOP_DIR" 2>/dev/null

# Refresh the icon cache so a newly added icon is picked up without a
# logout. Harmless when the theme directory has no cache to rebuild.
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -f -t "${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor" \
        >/dev/null 2>&1 || true
fi

echo "Installed: $ENTRY"

# Also drop a copy on the desktop, marked trusted so the file manager
# offers to run it rather than showing a text file.
DESK="$(desktop_dir)"
if [ -n "$DESK" ]; then
    cp "$ENTRY" "$DESK/$APP_ID.desktop"
    chmod +x "$DESK/$APP_ID.desktop"
    if command -v gio >/dev/null 2>&1; then
        gio set "$DESK/$APP_ID.desktop" metadata::trusted true 2>/dev/null \
            && echo "Marked trusted."
    fi
    echo "Desktop icon: $DESK/$APP_ID.desktop"
else
    echo
    echo "No desktop folder found, so no desktop icon was created."
    echo "The applications-menu entry above still works - search for"
    echo "\"Diagnostic\" in your activities/app menu."
fi

echo
echo "It should appear in your applications menu straight away."
echo
echo "If no icon appeared on the desktop itself:"
echo "  * Many GNOME versions do not show desktop icons at all unless"
echo "    the 'Desktop Icons NG (DING)' extension is enabled. The"
echo "    applications menu entry is unaffected."
echo "  * If it shows as a plain text file, right-click it and choose"
echo "    'Allow Launching'. Some desktops want that click even after"
echo "    the file has been marked trusted."
