package collectors

import (
	"testing"
	"time"
)

// Fixtures below are real output captured during the field campaign (Zorin
// laptop, Win 11 client, Windows Server DC) or reproduced verbatim from the
// vendor's documented format. The point of this file is that a parsing bug
// should fail HERE, on any machine, rather than on a customer's laptop.

// --------------------------------------------------------------- Linux

func TestDefaultGatewayFromRoute(t *testing.T) {
	// Captured from the laptop: gateway 192.168.1.1 as little-endian hex.
	const routeTable = `Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT
wlp2s0	00000000	01B2A8C0	0003	0	0	600	00000000	0	0	0
wlp2s0	00B2A8C0	00000000	0001	0	0	600	00FFFFFF	0	0	0
`
	if got := DefaultGatewayFromRoute(routeTable); got != "192.168.1.1" {
		t.Errorf("gateway = %q, want 192.168.1.1", got)
	}

	// A machine with an address but NO default route must yield "", not a
	// plausible-looking wrong answer.
	const noDefault = `Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT
eth0	0032A8C0	00000000	0001	0	0	0	00FFFFFF	0	0	0
`
	if got := DefaultGatewayFromRoute(noDefault); got != "" {
		t.Errorf("no default route should give empty, got %q", got)
	}

	// Garbage in, silence out.
	if got := DefaultGatewayFromRoute("not a route table"); got != "" {
		t.Errorf("garbage gave %q", got)
	}
}

func TestHexPort(t *testing.T) {
	cases := map[string]int{
		"0100007F:0035": 53,  // 127.0.0.1:53
		"00000000:01BB": 443, // :443
		"00000000:0016": 22,  // :22
		"junk":          0,   // no colon
		"00000000:ZZZZ": 0,   // unparsable
	}
	for in, want := range cases {
		if got := HexPort(in); got != want {
			t.Errorf("HexPort(%q) = %d, want %d", in, got, want)
		}
	}
}

func TestResolvConfIgnoresComments(t *testing.T) {
	const conf = `# Generated by NetworkManager
nameserver 192.168.1.1
#nameserver 8.8.8.8
; nameserver 1.1.1.1
nameserver fd00::1
search lan
`
	got := ResolvConfServers(conf)
	if len(got) != 2 || got[0] != "192.168.1.1" || got[1] != "fd00::1" {
		t.Errorf("servers = %v, want the two uncommented entries", got)
	}
	// A commented-out resolver must NOT count as configured — otherwise a
	// machine with no working DNS reads as healthy.
	for _, s := range got {
		if s == "8.8.8.8" || s == "1.1.1.1" {
			t.Errorf("commented resolver %s was treated as configured", s)
		}
	}
}

func TestProcNetWirelessTrailingDots(t *testing.T) {
	// Captured from the laptop: quality 70., level -37. (note the dots).
	const contents = `Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
wlp2s0: 0000   70.  -37.  -256        0      0      0      0      0        0
`
	iface, quality, signal, present := ProcNetWireless(contents)
	if !present || iface != "wlp2s0" {
		t.Fatalf("iface = %q present = %v", iface, present)
	}
	if quality != 70 || signal != -37 {
		t.Errorf("quality = %v signal = %v, want 70 and -37", quality, signal)
	}

	// A machine with no wireless interface has only the two header lines.
	const headersOnly = `Inter-| sta-|   Quality        |   Discarded packets
 face | tus | link level noise |  nwid  crypt   frag
`
	if _, _, _, present := ProcNetWireless(headersOnly); present {
		t.Error("headers-only file reported a wireless interface")
	}
}

// --------------------------------------------------------------- Windows

func TestSCServiceRunningIsJudgedByNumber(t *testing.T) {
	const running = `SERVICE_NAME: spooler
        TYPE               : 110  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, PAUSABLE, ACCEPTS_SHUTDOWN)
`
	if ok, measured := SCServiceRunning(running); !ok || !measured {
		t.Error("running spooler not detected")
	}

	const stopped = `SERVICE_NAME: spooler
        TYPE               : 110  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
`
	if ok, measured := SCServiceRunning(stopped); ok || !measured {
		t.Error("stopped spooler misread")
	}

	// French Windows: the WORD changes, the NUMBER does not. This is the
	// exact class of bug that made nltest lie on the DC.
	const french = `SERVICE_NAME: spooler
        TYPE               : 110  WIN32_OWN_PROCESS
        ÉTAT               : 4  EN COURS D'EXÉCUTION
`
	if ok, measured := SCServiceRunning(french); !ok || !measured {
		t.Error("localized output broke the state read — must judge by the number")
	}

	// Unreadable output must report "not measured", never "stopped".
	if _, measured := SCServiceRunning("access denied"); measured {
		t.Error("garbage reported as a measurement")
	}
}

func TestNetshValue(t *testing.T) {
	const out = `
There is 1 interface on the system:

    Name                   : Wi-Fi
    Description            : Intel(R) Wi-Fi 6 AX201
    GUID                   : 6c6f2b1e-0000-0000-0000-000000000000
    Physical address       : a4:83:e7:11:22:33
    State                  : connected
    SSID                   : HomeNet
    BSSID                  : 02:1a:20:fa:53:5f
    Radio type             : 802.11ac
    Channel                : 36
    Signal                 : 92%
`
	cases := map[string]string{
		"Name":    "Wi-Fi",
		"SSID":    "HomeNet",
		"BSSID":   "02:1a:20:fa:53:5f",
		"Channel": "36",
		"Signal":  "92%",
	}
	for key, want := range cases {
		if got := NetshValue(out, key); got != want {
			t.Errorf("NetshValue(%q) = %q, want %q", key, got, want)
		}
	}
	if got := NetshValue(out, "Nonexistent"); got != "" {
		t.Errorf("missing key gave %q", got)
	}
}

func TestDsregcmdState(t *testing.T) {
	// Captured shape from the Win 11 client joined to corp.local.
	const joined = `
+----------------------------------------------------------------------+
| Device State                                                         |
+----------------------------------------------------------------------+

             AzureAdJoined : NO
          EnterpriseJoined : NO
              DomainJoined : YES
                DomainName : CORP
`
	dj, az, realm := DsregcmdState(joined)
	if !dj || az || realm != "CORP" {
		t.Errorf("joined = %v azure = %v realm = %q", dj, az, realm)
	}

	const standalone = `
             AzureAdJoined : NO
              DomainJoined : NO
`
	if dj, _, realm := DsregcmdState(standalone); dj || realm != "" {
		t.Errorf("standalone machine reported as joined (%v, %q)", dj, realm)
	}
}

func TestRegValueHex(t *testing.T) {
	const out = `
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient
    EnableMulticast    REG_DWORD    0x0
`
	v, ok := RegValueHex(out, "EnableMulticast")
	if !ok || v != 0 {
		t.Errorf("EnableMulticast = %d ok = %v, want 0 true", v, ok)
	}
	if _, ok := RegValueHex(out, "SomethingElse"); ok {
		t.Error("absent value reported as present")
	}
}

func TestPnPPowerSavingSenseIsNotInverted(t *testing.T) {
	// 0x18 set = machine may NOT power the NIC off = power saving disabled.
	const disabled = `
    PnPCapabilities    REG_DWORD    0x18
`
	if saving, measured := PnPPowerSaving(disabled); saving || !measured {
		t.Error("0x18 means power saving is OFF")
	}

	const enabled = `
    PnPCapabilities    REG_DWORD    0x0
`
	if saving, measured := PnPPowerSaving(enabled); !saving || !measured {
		t.Error("0x0 means power saving is allowed")
	}

	// Virtio adapters expose nothing — must be unmeasured, not "fine".
	if _, measured := PnPPowerSaving("ERROR: The system was unable to find..."); measured {
		t.Error("absent PnPCapabilities reported as a measurement")
	}
}

func TestPrintQueueCounts(t *testing.T) {
	got := PrintQueueCounts("JOBS=4;ERR=2;OLD=1\n")
	if got["depth"] != 4 || got["errored"] != 2 || got["stale"] != 1 {
		t.Errorf("counts = %v", got)
	}

	// An unreadable queue yields NO keys — the caller must be able to tell
	// "empty queue" from "could not look".
	if len(PrintQueueCounts("Get-Printer : Access is denied")) != 0 {
		t.Error("error text produced counts")
	}
}

// Field regression (Win 11, 0.9.0): the IP_ADAPTER_INFO struct walk reported
// the DHCP server as "255" where the real answer was 10.0.0.10. The registry
// is the documented, locale-proof source; this pins its format.
func TestDHCPFromRegistry(t *testing.T) {
	const out = `
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{aaaa-1111}
    DhcpIPAddress    REG_SZ    10.0.0.50
    DhcpServer    REG_SZ    10.0.0.10
    LeaseTerminatesTime    REG_DWORD    0x689c1f00

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{bbbb-2222}
    DhcpIPAddress    REG_SZ    0.0.0.0
`
	leases := DHCPFromRegistry(out)
	if len(leases) != 2 {
		t.Fatalf("want 2 interface blocks, got %d: %+v", len(leases), leases)
	}
	var found bool
	for _, l := range leases {
		if l.IPAddress == "10.0.0.50" {
			found = true
			if l.Server != "10.0.0.10" {
				t.Errorf("server = %q, want 10.0.0.10 (the field bug reported \"255\")", l.Server)
			}
			if l.ExpiryUTC != 0x689c1f00 {
				t.Errorf("expiry = %d, want the parsed REG_DWORD", l.ExpiryUTC)
			}
		}
	}
	if !found {
		t.Error("the interface holding the lease was not parsed")
	}
}

// The second opinion on the Windows medium. If this parser silently returns
// nothing, confirmWinMedium refuses to confirm — which blocks a rule rather
// than firing a wrong one, and that is the direction we want it to fail in.
func TestWlanInterfaceNames(t *testing.T) {
	const english = `
There is 1 interface on the system:

    Name                   : Wi-Fi
    Description            : Intel(R) Wi-Fi 6 AX201 160MHz
    GUID                   : 6c4f2f2a-1b1e-4b0a-9f0e-1f2d3c4b5a69
    Physical address       : a4:c3:f0:11:22:33
    State                  : connected
    SSID                   : corp-wifi
    Signal                 : 78%
`
	got := WlanInterfaceNames(english)
	if len(got) != 1 || got[0] != "Wi-Fi" {
		t.Errorf("english: got %v, want [Wi-Fi]", got)
	}

	// French, because this is the third localisation bug family in this
	// project and the first two shipped.
	const french = `
Il y a 1 interface sur le système :

    Nom                    : Wi-Fi
    Description            : Intel(R) Wi-Fi 6 AX201 160MHz
    État                   : connecté
`
	if got := WlanInterfaceNames(french); len(got) != 1 || got[0] != "Wi-Fi" {
		t.Errorf("french: got %v, want [Wi-Fi]", got)
	}

	// Two adapters, both named.
	const two = `
    Name                   : Wi-Fi
    State                  : connected
    Name                   : Wi-Fi 2
    State                  : disconnected
`
	if got := WlanInterfaceNames(two); len(got) != 2 {
		t.Errorf("two adapters: got %v", got)
	}

	// A locale whose key we do not recognise must yield NOTHING, so the
	// caller declines to confirm rather than guessing.
	const unknownLocale = `
    Nazwa                  : Wi-Fi
    Stan                   : połączony
`
	if got := WlanInterfaceNames(unknownLocale); len(got) != 0 {
		t.Errorf("unknown locale should yield no names, got %v", got)
	}

	if got := WlanInterfaceNames(""); len(got) != 0 {
		t.Errorf("empty input: got %v", got)
	}
	if got := WlanInterfaceNames("There is no wireless interface on the system."); len(got) != 0 {
		t.Errorf("no-wireless message: got %v", got)
	}
}

// The event miner is the only tier that answers "it drops now and then"
// without sitting and waiting. It had no tests at all, and the phrases below
// ARE the detector: a distribution wording a carrier loss differently produces
// a silent zero, which reads as "this link is stable".
func TestMineEvents(t *testing.T) {
	// Captured shapes from the Zorin laptop run that found 126 flaps.
	lines := []string{
		"1721312345.123456 zorin kernel: e1000e 0000:00:1f.6 eno1: Link is Down",
		"1721312350.100000 zorin kernel: e1000e 0000:00:1f.6 eno1: NIC Link is Up 1000 Mbps Full Duplex",
		"1721312400.000000 zorin kernel: igb 0000:01:00.0 enp1s0: igb: enp1s0 NIC Link is Down",
		"1721315999.000000 zorin wpa_supplicant[812]: wlp2s0: CTRL-EVENT-DISCONNECTED bssid=aa:bb:cc:dd:ee:ff reason=3",
		"1721316000.000000 zorin wpa_supplicant[812]: wlp2s0: Deauthenticated by local choice (reason=3)",
		"1721316100.000000 zorin dhclient[900]: No DHCPOFFERS received.",
		"1721316200.000000 zorin NetworkManager[700]: <warn> dhcp4: request timed out",
		"1721316300.000000 zorin systemd[1]: Started Some Unrelated Service.",
	}
	// Attributed to eno1 (bug #31): of the two down-events, only ONE is on the
	// interface in use. The other belongs to enp1s0 and is reported separately
	// rather than added to this machine's total. "Link is Up" never counts.
	got := MineEvents(lines, "eno1")
	if got.LinkFlaps != 1 {
		t.Errorf("primary flaps = %d, want 1 — the other NIC's flap must not be added", got.LinkFlaps)
	}
	if len(got.OtherFlaps) == 0 {
		t.Error("the other interface's flap vanished instead of being reported separately")
	}
	if got.WifiDisconnects != 2 {
		t.Errorf("wifi disconnects = %d, want 2", got.WifiDisconnects)
	}
	if got.DHCPFailures != 2 {
		t.Errorf("dhcp failures = %d, want 2", got.DHCPFailures)
	}

	// Other spellings of the same physical event, which is where a silent zero
	// would come from.
	for _, l := range []string{
		"1721312345.0 host kernel: eth0: carrier lost",
		"1721312345.0 host kernel: bond0: lost carrier",
	} {
		if c := MineEvents([]string{l}, ifaceOf(l)); c.LinkFlaps != 1 {
			t.Errorf("did not count %q as a flap", l)
		}
	}

	// Clustering only uses lines that actually carry a timestamp.
	if len(got.FlapHours) == 0 {
		t.Error("timestamped flaps were not bucketed, so the peak window is lost")
	}

	// Syslog lines have no unix prefix; they must still COUNT, and must not be
	// bucketed into 1970 as though they all happened at once.
	sys := MineEvents([]string{"Jul 19 09:14:02 host kernel: eth0: Link is Down"}, "eth0")
	if sys.LinkFlaps != 1 {
		t.Error("syslog-format line was not counted")
	}
	if len(sys.FlapHours) != 0 {
		t.Error("an undated line was bucketed into a fake hour")
	}

	if c := MineEvents(nil, "eno1"); c.LinkFlaps+c.WifiDisconnects+c.DHCPFailures != 0 {
		t.Error("no input produced counts from nowhere")
	}
}

func TestSplitUnixTS(t *testing.T) {
	ts, rest := SplitUnixTS("1721312345.123456 host msg here")
	if ts != 1721312345 || rest != "host msg here" {
		t.Errorf("got (%d, %q)", ts, rest)
	}
	if ts, _ := SplitUnixTS("Jul 19 09:14:02 host msg"); ts != 0 {
		t.Errorf("syslog line yielded ts %d, want 0", ts)
	}
	if ts, rest := SplitUnixTS("noSpace"); ts != 0 || rest != "noSpace" {
		t.Errorf("got (%d, %q)", ts, rest)
	}
}

// Bug #23: the input policy used to default to "accept" and only be revised to
// "drop", so a ruleset that never stated one was reported as wide open.
func TestFirewallPolicyIsNeverAssumed(t *testing.T) {
	// nft doing only NAT: no filter input hook anywhere.
	natOnly := `
table ip nat {
	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		oifname "eth0" masquerade
	}
}`
	s := SummariseNftables(natOnly)
	if s.InputPolicy != "" {
		t.Errorf("input policy %q invented from a ruleset with no input hook", s.InputPolicy)
	}

	drop := `
table inet filter {
	chain input {
		type filter hook input priority 0; policy drop;
		ct state established,related accept
		tcp dport 22 accept
	}
}`
	s = SummariseNftables(drop)
	if s.InputPolicy != "drop" {
		t.Errorf("input policy = %q, want drop", s.InputPolicy)
	}
	if s.RuleCount < 2 {
		t.Errorf("rule count = %d, want the two accept rules counted", s.RuleCount)
	}

	// reject is a real nft policy and used to be silently read as accept.
	reject := "\tchain input {\n\t\ttype filter hook input priority 0; policy reject;\n\t}"
	if got := SummariseNftables(reject).InputPolicy; got != "reject" {
		t.Errorf("reject policy read as %q", got)
	}

	if got := SummariseNftables("").Measured; got {
		t.Error("an empty ruleset reported itself as measured")
	}
}

func TestSummariseIptables(t *testing.T) {
	out := `-P INPUT DROP
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT`
	s := SummariseIptables(out)
	if s.InputPolicy != "drop" {
		t.Errorf("input policy = %q, want drop", s.InputPolicy)
	}
	if s.RuleCount != 3 {
		t.Errorf("rule count = %d, want 3 (two -A plus one -N)", s.RuleCount)
	}
	if !s.Measured {
		t.Error("a real ruleset was not marked measured")
	}
	// Policies only, no rules: measured, but nothing to count.
	if s := SummariseIptables("-P INPUT ACCEPT"); s.RuleCount != 0 || s.InputPolicy != "accept" {
		t.Errorf("policy-only ruleset: count=%d policy=%q", s.RuleCount, s.InputPolicy)
	}
}

// dhclient APPENDS leases, so a file holds every lease the interface ever had.
// Taking the first match reports an expiry from months ago and claims the
// lease has lapsed on a machine whose networking is fine.
func TestLeaseExpiryTakesTheNewest(t *testing.T) {
	const leases = `
lease {
  interface "eno1";
  option dhcp-server-identifier 192.168.1.1;
  expire 3 2026/01/02 12:00:00;
}
lease {
  interface "eno1";
  option dhcp-server-identifier 192.168.1.1;
  expire 5 2026/07/22 09:30:00;
}
lease {
  interface "eno1";
  expire 4 2026/03/15 18:00:00;
}
`
	got, ok := LeaseExpiryFrom(leases)
	if !ok {
		t.Fatal("no expiry found in a file full of them")
	}
	want := time.Date(2026, 7, 22, 9, 30, 0, 0, time.UTC)
	if !got.Equal(want) {
		t.Errorf("expiry = %s, want the NEWEST lease %s", got, want)
	}

	if _, ok := LeaseExpiryFrom("lease {\n  interface \"eno1\";\n}"); ok {
		t.Error("a lease with no expire line reported one anyway")
	}
	if _, ok := LeaseExpiryFrom(""); ok {
		t.Error("empty input produced an expiry")
	}
	// A malformed date must not become "expired now", which would fire a
	// lease-expiry finding on a healthy machine.
	if _, ok := LeaseExpiryFrom("expire 3 not/a/date 99:99:99;"); ok {
		t.Error("garbage date parsed as a real expiry")
	}
}

func TestLeaseServerFromBothFormats(t *testing.T) {
	// systemd-networkd
	if got, ok := LeaseServerFrom("ADDRESS=192.168.1.50\nSERVER_ADDRESS=192.168.1.1\n"); !ok || got != "192.168.1.1" {
		t.Errorf("systemd lease: got %q ok=%v", got, ok)
	}
	// dhclient
	if got, ok := LeaseServerFrom(`  option dhcp-server-identifier 10.0.0.1;`); !ok || got != "10.0.0.1" {
		t.Errorf("dhclient lease: got %q ok=%v", got, ok)
	}
	// A lease file with no server must report NOT MEASURED, never "" as a
	// value — "no DHCP server" reads as broken DHCP.
	if _, ok := LeaseServerFrom("ADDRESS=192.168.1.50\n"); ok {
		t.Error("a lease with no server identifier claimed to have found one")
	}
	// The shape of the bug that shipped once: a truncated value.
	if _, ok := LeaseServerFrom("SERVER_ADDRESS=255\n"); ok {
		t.Error(`"255" was accepted as a DHCP server address — that exact value shipped once`)
	}
}

func TestPlausibleIPv4(t *testing.T) {
	for _, good := range []string{"192.168.1.1", "10.0.0.1", "0.0.0.0", "255.255.255.255"} {
		if !plausibleIPv4(good) {
			t.Errorf("%q rejected", good)
		}
	}
	for _, bad := range []string{"255", "192.168.1", "192.168.1.1.1", "192.168.1.256",
		"", "abc", "192.168.1.x", "1921.68.1.1"} {
		if plausibleIPv4(bad) {
			t.Errorf("%q accepted", bad)
		}
	}
}

// ifaceOf is a test helper: the fixtures above name several interfaces.
func ifaceOf(line string) string { return IfaceInLogLine(line) }

// Bug #31 (Zorin, 0.9.22) — the most instructive bug in this project so far.
//
// The counter counted every "link is down" line in the journal. On a laptop
// working perfectly over Wi-Fi, 46 of them belonged to enp7s0: an unplugged
// Realtek ethernet port, which is what r8169 does with an empty socket. The
// tool reported "the link went down repeatedly" and the finding was cited for
// weeks as a genuine fault the tool had found.
//
// The number was right. The subject of the sentence was wrong.
func TestFlapsAreAttributedToTheInterfaceInUse(t *testing.T) {
	// The real shape, from popeye-mk's journal.
	lines := []string{
		"1721400000.0 host kernel: r8169 0000:07:00.0 enp7s0: Link is Down",
		"1721400100.0 host kernel: r8169 0000:07:00.0 enp7s0: Link is Down",
		"1721400200.0 host kernel: r8169 0000:07:00.0 enp7s0: Link is Down",
		"1721400300.0 host kernel: iwlwifi 0000:02:00.0 wlp2s0: Link is Down",
	}

	// On Wi-Fi: only the ONE wireless flap is this machine's connection.
	onWifi := MineEvents(lines, "wlp2s0")
	if onWifi.LinkFlaps != 1 {
		t.Errorf("primary flaps = %d, want 1 — the unplugged ethernet port must not count",
			onWifi.LinkFlaps)
	}
	if onWifi.OtherFlaps["enp7s0"] != 3 {
		t.Errorf("enp7s0 flaps = %d, want 3 reported separately", onWifi.OtherFlaps["enp7s0"])
	}
	if !onWifi.Attributed {
		t.Error("attribution was possible and was not claimed")
	}

	// Plugged into ethernet instead: the same lines mean the opposite.
	onWired := MineEvents(lines, "enp7s0")
	if onWired.LinkFlaps != 3 {
		t.Errorf("wired primary flaps = %d, want 3", onWired.LinkFlaps)
	}
	if onWired.OtherFlaps["wlp2s0"] != 1 {
		t.Errorf("wifi flaps should now be the OTHER interface: %v", onWired.OtherFlaps)
	}

	// No primary known: count, but do not claim they are the machine's link.
	// Silence would hide a real fault; attribution would invent one.
	unknown := MineEvents(lines, "")
	if unknown.Attributed {
		t.Error("claimed attribution with no primary interface")
	}
	if unknown.LinkFlaps != 4 {
		t.Errorf("unattributed count = %d, want all 4 visible as evidence", unknown.LinkFlaps)
	}

	// The peak-hour clustering must only see the primary's flaps, or the
	// "it happens around 14:00" claim describes the wrong interface.
	if len(onWifi.FlapHours) > 1 {
		t.Errorf("peak-hour buckets polluted by other interfaces: %v", onWifi.FlapHours)
	}
}

func TestIfaceInLogLine(t *testing.T) {
	for _, tc := range []struct{ line, want string }{
		{"r8169 0000:07:00.0 enp7s0: Link is Down", "enp7s0"},
		{"e1000e 0000:00:1f.6 eno1: Link is Down", "eno1"},
		{"host systemd-networkd[700]: wlp2s0: Lost carrier", "wlp2s0"},
		{"host kernel: eth0: carrier lost", "eth0"},
		// Nothing name-shaped before the message: must return "" so the caller
		// files it as unattributable rather than blaming the primary.
		{"kernel: Link is Down", ""},
		{"Link is Down", ""},
		{"", ""},
	} {
		if got := IfaceInLogLine(tc.line); got != tc.want {
			t.Errorf("IfaceInLogLine(%q) = %q, want %q", tc.line, got, tc.want)
		}
	}
}
